from __future__ import annotations

from typing import Any, Dict, List
from uuid import uuid4

from app.core.substrate import SubstrateState
from app.core.order_governor import OrderGovernor
from app.models.gates import Gate, EmergentLink

class AutonomyKernel:
    def __init__(self, substrate: SubstrateState, governor: OrderGovernor):
        self.substrate = substrate
        self.governor = governor
        self.action_log: List[Dict[str, Any]] = []

    def ingest_event(self, source: str, event_type: str, content: str, urgency: float, novelty: float, metadata: Dict[str, Any]) -> Dict[str, Any]:
        gate_type = self.classify_event(event_type, content, metadata)
        gate = Gate(
            type=gate_type,
            title=content[:80] or "Untitled event",
            description=content,
            metadata={
                "source": source,
                "urgency": urgency,
                "novelty": novelty,
                **metadata,
            },
        )
        self.substrate.add_gate(gate)

        if urgency > 0.65:
            q = Gate(
                type="Question",
                title=f"What order is required for: {gate.title}?",
                description="Autogenerated reflection question from a high-urgency event.",
                links=[gate.id],
                metadata={"source_gate": gate.id, "urgency": urgency},
            )
            self.substrate.add_gate(q)

        return {"gate": gate.to_dict(), "state": self.substrate.snapshot()}

    def classify_event(self, event_type: str, content: str, metadata: Dict[str, Any]) -> str:
        text = f"{event_type} {content}".lower()
        if any(w in text for w in ["problem", "risk", "broken", "pain", "issue"]):
            return "Problem"
        if any(w in text for w in ["solution", "fix", "build", "implement", "deploy"]):
            return "Solution"
        if any(w in text for w in ["because", "therefore", "argue", "evidence", "reason"]):
            return "Argument"
        if any(w in text for w in ["api", "data", "metric", "source", "telemetry"]):
            return "DataSource"
        return metadata.get("gate_type", "Problem")

    def step(self, allow_execution: bool = False) -> Dict[str, Any]:
        self.substrate.tick += 1
        field = self.substrate.snapshot()

        proposed_intensity = self.propose_intensity(field)
        order = self.governor.decide(field, proposed_intensity)
        action = self.propose_action(field, order.allowed, allow_execution)

        if order.allowed:
            self.discover_links()

        record = {
            "tick": self.substrate.tick,
            "field": field,
            "order": order.__dict__,
            "action": action,
            "executed": bool(order.allowed and allow_execution and action["execution_mode"] == "reversible"),
        }
        self.action_log.append(record)
        self.substrate.memory.append({"event": "autonomy_step", "record": record, "tick": self.substrate.tick})
        return record

    def propose_intensity(self, field: Dict[str, Any]) -> float:
        coherence = field["coherence"]
        novelty = field["novelty"]
        contradiction = field["contradiction_pressure"]
        return max(0.0, min(1.0, 0.35 + 0.45 * novelty + 0.35 * coherence - 0.40 * contradiction))

    def propose_action(self, field: Dict[str, Any], ordered: bool, allow_execution: bool) -> Dict[str, Any]:
        if not ordered:
            return {
                "id": f"A-{uuid4().hex[:8]}",
                "type": "ORDERING",
                "description": "Generate clarifying questions and request more grounding before execution.",
                "execution_mode": "reflection_only",
            }

        if field["coherence"] > 0.82 and field["novelty"] > 0.55:
            return {
                "id": f"A-{uuid4().hex[:8]}",
                "type": "EMERGENCE",
                "description": "Create emergent links between high-salience gates.",
                "execution_mode": "reversible",
            }

        return {
            "id": f"A-{uuid4().hex[:8]}",
            "type": "INTEGRATION",
            "description": "Improve graph coherence by linking problems, solutions, arguments, and data.",
            "execution_mode": "reversible",
        }

    def discover_links(self) -> None:
        gates = list(self.substrate.gates.values())
        if len(gates) < 2:
            return

        recent = gates[-8:]
        for a in recent:
            for b in recent:
                if a.id == b.id:
                    continue
                if a.type == "Problem" and b.type in {"Solution", "Argument", "DataSource"}:
                    existing = any(l.from_gate == a.id and l.to_gate == b.id for l in self.substrate.links.values())
                    if not existing:
                        self.substrate.add_link(EmergentLink(a.id, b.id, "requires", confidence=0.62))
                        return

    def emergence_report(self) -> Dict[str, Any]:
        field = self.substrate.snapshot()
        readiness = min(1.0, 0.65 * field["coherence"] + 0.35 * field["novelty"] - 0.25 * field["contradiction_pressure"])
        return {
            "readiness": round(max(0.0, readiness), 4),
            "field": field,
            "recommendation": (
                "Permit bounded autonomous emergence."
                if readiness >= 0.82
                else "Increase graph coherence before expanding autonomy."
            ),
            "recent_actions": self.action_log[-10:],
        }
