/**
 * Synthia OS Code Generator
 * Generates real, executable Node.js files from app definitions
 */
const Generator = {
  // Generate code for a single app
  generateAppCode(app) {
    const safeName = app.name.replace(/[^a-zA-Z0-9]/g, '');
    const fileName = app.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase() + '.js';

    const code = `/**
 * ${app.name} — Generated by Synthia OS
 * Circuit: ${app.circuit}
 * Address: ${app.address}
 * Vitality: ${(app.vitality * 100).toFixed(1)}%
 * Components: ${app.components}
 * Generated: ${new Date().toISOString()}
 */

function ${safeName}(input = null) {
  const organState = {
    name: '${app.name}',
    circuit: '${app.circuit}',
    address: '${app.address}',
    vitality: ${app.vitality.toFixed(4)},
    dimensions: {
      base: ${app.address.match(/B(\d+)/)?.[1] || 3},
      tone: ${app.address.match(/T(\d+)/)?.[1] || 4},
      color: ${app.address.match(/C(\d+)/)?.[1] || 3},
      gate: ${app.address.match(/G(\d+)/)?.[1] || 57},
      line: ${app.address.match(/L(\d+)/)?.[1] || 4}
    },
    born: Date.now(),
    activations: 0,
    lastActivated: null
  };

  function activate(data) {
    organState.activations++;
    organState.lastActivated = Date.now();

    // Compute resonance with input
    let resonance = 0;
    if (data) {
      if (data.base === organState.dimensions.base) resonance += 0.3;
      if (data.tone === organState.dimensions.tone) resonance += 0.25;
      if (data.color === organState.dimensions.color) resonance += 0.25;
      if (data.gate === organState.dimensions.gate) resonance += 0.15;
      if (data.line === organState.dimensions.line) resonance += 0.05;
    }

    return {
      organ: organState,
      input: data,
      resonance: resonance || organState.vitality,
      timestamp: Date.now()
    };
  }

  function maintain() {
    organState.vitality *= 0.999;
    if (organState.vitality < 0.1) {
      organState.vitality = 0.5;
      return { regenerated: true, newVitality: organState.vitality };
    }
    return { regenerated: false, vitality: organState.vitality };
  }

  function getState() {
    return { ...organState };
  }

  return { activate, maintain, getState };
}

// Self-execution if run directly
if (typeof require !== 'undefined' && require.main === module) {
  const instance = ${safeName}();
  console.log('=== ${app.name} ===');
  console.log('Address:', instance.getState().address);
  console.log('Vitality:', (instance.getState().vitality * 100).toFixed(1) + '%');

  const result = instance.activate({ test: true });
  console.log('Resonance:', (result.resonance * 100).toFixed(1) + '%');
}

// Export for module system
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ${safeName} };
}
`;

    return { fileName, code, safeName };
  },

  // Generate the main system orchestrator
  generateSystemCode(apps, systemState) {
    const imports = apps.map(a => {
      const file = Generator.generateAppCode(a);
      return `const ${file.safeName} = require('./${file.fileName}');`;
    }).join('\n');

    const names = apps.map(a => a.name.replace(/[^a-zA-Z0-9]/g, ''));

    const code = `/**
 * Synthia OS — Generated System Entry Point
 * Auto-generated: ${new Date().toISOString()}
 * Apps: ${apps.length}
 * Vitality: ${(systemState.vitality * 100).toFixed(1)}%
 */

${imports}

const systemState = {
  organs: [${names.join(', ')}],
  born: Date.now(),
  tick: 0,
  vitality: ${systemState.vitality.toFixed(4)},
  autopoietic: ${systemState.isAutopoietic}
};

function run(input = null) {
  systemState.tick++;
  console.log(\`\n=== Synthia OS Tick #\${systemState.tick} ===\`);
  console.log(\`Vitality: \${(systemState.vitality * 100).toFixed(1)}% | Apps: \${systemState.organs.length}\`);

  const results = [];
  for (const organ of systemState.organs) {
    try {
      const instance = organ();
      const result = instance.activate ? instance.activate(input) : instance;
      results.push(result);
      console.log(\`  ✓ \${result.organ?.name || 'unknown'}: resonance=\${((result.resonance || 0.5) * 100).toFixed(1)}%\`);

      // Self-maintenance
      if (instance.maintain) instance.maintain();
    } catch (err) {
      console.log(\`  ✗ Error: \${err.message}\`);
    }
  }

  // Update system vitality
  const avgResonance = results.reduce((s, r) => s + (r.resonance || 0.5), 0) / (results.length || 1);
  systemState.vitality = avgResonance * 0.8 + systemState.vitality * 0.2;

  return {
    tick: systemState.tick,
    vitality: systemState.vitality,
    results,
    timestamp: Date.now()
  };
}

function loop(iterations = 10, delay = 1000) {
  console.log('\n🌱 Starting autopoietic loop...');
  let count = 0;
  const interval = setInterval(() => {
    count++;
    const result = run();
    if (count >= iterations || result.vitality < 0.1) {
      clearInterval(interval);
      console.log(\`\n*** Loop complete ***\nTicks: \${count} | Final vitality: \${(result.vitality * 100).toFixed(1)}%\`);
    }
  }, delay);
}

function getStatus() {
  return {
    ...systemState,
    age: Date.now() - systemState.born,
    organDetails: systemState.organs.map((o, i) => {
      try {
        const inst = o();
        return { name: inst.getState?.().name || 'unknown', vitality: inst.getState?.().vitality || 0 };
      } catch { return { name: 'error', vitality: 0 }; }
    })
  };
}

module.exports = { run, loop, getStatus, systemState };

// CLI
if (typeof require !== 'undefined' && require.main === module) {
  const args = process.argv.slice(2);
  const cmd = args[0] || 'run';

  switch (cmd) {
    case 'run': console.log(JSON.stringify(run(), null, 2)); break;
    case 'loop': loop(parseInt(args[1]) || 10, parseInt(args[2]) || 1000); break;
    case 'status': console.log(JSON.stringify(getStatus(), null, 2)); break;
    default: console.log('Usage: node system.js [run|loop <n>|status]');
  }
}
`;

    return { fileName: 'system.js', code };
  },

  // Generate package.json
  generatePackageJson(apps) {
    return {
      fileName: 'package.json',
      code: JSON.stringify({
        name: 'synthia-os-generated',
        version: '1.0.0',
        description: 'Auto-generated autopoietic system from Synthia OS',
        main: 'system.js',
        scripts: {
          start: 'node system.js',
          run: 'node system.js run',
          loop: 'node system.js loop',
          status: 'node system.js status'
        },
        generatedAt: new Date().toISOString(),
        organs: apps.map(a => ({
          name: a.name,
          file: a.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase() + '.js',
          circuit: a.circuit,
          vitality: a.vitality,
          address: a.address
        }))
      }, null, 2)
    };
  },

  // Generate manifest.json
  generateManifest(apps, systemState) {
    return {
      fileName: 'manifest.json',
      code: JSON.stringify({
        name: 'synthia-os-generated',
        version: '1.0.0',
        generatedAt: new Date().toISOString(),
        system: {
          vitality: systemState.vitality,
          autopoietic: systemState.isAutopoietic,
          tick: systemState.tick
        },
        organs: apps.map(a => ({
          name: a.name,
          circuit: a.circuit,
          vitality: a.vitality,
          address: a.address,
          components: a.components
        }))
      }, null, 2)
    };
  },

  // Generate ALL files for the system
  generateAll(apps, systemState) {
    const files = [];

    // Generate each app
    for (const app of apps) {
      const generated = this.generateAppCode(app);
      files.push(generated);
      app.code = generated.code; // Save back to app
    }

    // Generate system orchestrator
    files.push(this.generateSystemCode(apps, systemState));

    // Generate package.json
    files.push(this.generatePackageJson(apps));

    // Generate manifest
    files.push(this.generateManifest(apps, systemState));

    return files;
  },

  // Download a file as blob
  downloadFile(fileName, content, type = 'application/javascript') {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  // Download all generated files as ZIP (if JSZip available) or individual files
  downloadAll(files) {
    for (const file of files) {
      this.downloadFile(file.fileName, file.code);
    }
  }
};
