/**
 * MRNN Code Generator
 * Generates executable Node.js modules from the system's structural memory.
 * 
 * The system doesn't just visualize — it PRODUCES CODE.
 * Each "organ" in the system body becomes a .js file.
 * Each "component" becomes an exported function/class.
 * The connections between organs become imports/exports.
 * 
 * The generated code is:
 * - importable via require()
 * - runnable via node
 * - self-referential (the system can ingest its own output)
 * - morphological (structure reflects MRNN dimensions)
 * 
 * This is the core autopoietic act: the system produces the components
 * (code files) that produce the system.
 */

const fs = require('fs');
const path = require('path');

class MRNNCodeGenerator {
  constructor(ingestionEngine, outputDir = './dist') {
    this.ingestion = ingestionEngine;
    this.engine = ingestionEngine.engine;
    this.outputDir = outputDir;
    this.generatedFiles = [];
    this.moduleMap = new Map();
  }

  // ============================================================
  // GENERATE SYSTEM CODE
  // The main entry — generates ALL executable files from the body
  // ============================================================
  async generate() {
    console.log('\n🔨 GENERATING EXECUTABLE CODE from system body...');

    const body = this.ingestion.getSystemBody();
    console.log(`   → Generating from ${body.organCount} organs, ${body.connectionCount} connections`);

    // 1. Generate organ modules (one file per organ)
    const organFiles = [];
    for (const organ of body.organs) {
      const file = this.generateOrganModule(organ);
      organFiles.push(file);
    }

    // 2. Generate the main system entry point
    const mainFile = this.generateMainModule(body, organFiles);

    // 3. Generate the package manifest
    const manifestFile = this.generatePackageManifest(body, organFiles);

    // 4. Write all files to disk
    await this.writeFiles([...organFiles, mainFile, manifestFile]);

    // 5. Verify executability
    const verified = await this.verifyExecutability();

    console.log(`\n✅ Generated ${this.generatedFiles.length} executable files`);
    console.log(`   → Entry: ${path.join(this.outputDir, 'system.js')}`);
    console.log(`   → Run: node ${path.join(this.outputDir, 'system.js')}`);

    return {
      files: this.generatedFiles,
      entryPoint: path.join(this.outputDir, 'system.js'),
      verified,
      organCount: body.organCount
    };
  }

  // ============================================================
  // GENERATE ORGAN MODULE
  // Each organ becomes a standalone .js file with exports
  // ============================================================
  generateOrganModule(organ) {
    const { name, circuit, addresses, components, vitality, color } = organ;

    // Sanitize name for filename
    const fileName = name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase() + '.js';
    const moduleName = name.replace(/[^a-zA-Z0-9]/g, '_');

    // Determine the organ's MRNN dimensions from its first address
    const primaryAddress = addresses[0] || 'B3.T4.C3.G57.L4';
    const dims = this.parseAddress(primaryAddress) || { base: 3, tone: 4, color: 3, gate: 57, line: 4 };

    // Generate component exports
    const componentExports = components.map((comp, i) => {
      const compName = `${moduleName}_${comp.type}_${i}`;
      return this.generateComponentCode(comp, compName, dims);
    });

    // Generate the organ's main function
    const organCode = `
/**
 * Organ: ${name}
 * Circuit: ${circuit}
 * Primary Address: ${primaryAddress}
 * Vitality: ${(vitality * 100).toFixed(1)}%
 * Dimensions: Base=${dims.base}, Tone=${dims.tone}, Color=${dims.color}, Gate=${dims.gate}, Line=${dims.line}
 * 
 * AUTO-GENERATED by MRNN Autopoietic System
 * This file is a living component produced by the system's own metabolism.
 */

${componentExports.map(c => c.imports).filter(Boolean).join('\n')}

// ============================================================
// ORGAN STATE
// ============================================================
const organState = {
  name: '${name}',
  circuit: '${circuit}',
  address: '${primaryAddress}',
  vitality: ${vitality.toFixed(4)},
  dimensions: ${JSON.stringify(dims)},
  born: Date.now(),
  activations: 0,
  lastActivated: null
};

// ============================================================
// COMPONENT DEFINITIONS
// ============================================================
${componentExports.map(c => c.code).join('\n\n')}

// ============================================================
// ORGAN MAIN FUNCTION
// ============================================================
function ${moduleName}(input = null) {
  organState.activations++;
  organState.lastActivated = Date.now();

  // Resonance computation
  const resonance = computeResonance(input);

  // Component activation based on resonance
  const activeComponents = [];
  ${componentExports.map((c, i) => `
  if (resonance > ${(0.3 + i * 0.1).toFixed(1)}) {
    activeComponents.push(${c.name}(input));
  }`).join('')}

  return {
    organ: organState,
    resonance,
    activeComponents,
    timestamp: Date.now()
  };
}

// ============================================================
// RESONANCE COMPUTATION
// ============================================================
function computeResonance(input) {
  if (!input) return organState.vitality;

  // Simple resonance: how much does input match our dimensions?
  let match = 0;
  if (input.base === organState.dimensions.base) match += 0.3;
  if (input.tone === organState.dimensions.tone) match += 0.25;
  if (input.color === organState.dimensions.color) match += 0.25;
  if (input.gate === organState.dimensions.gate) match += 0.15;
  if (input.line === organState.dimensions.line) match += 0.05;

  return match;
}

// ============================================================
// SELF-MAINTENANCE
// ============================================================
function maintain() {
  // Decay vitality over time
  organState.vitality *= 0.999;

  // Regenerate if too low
  if (organState.vitality < 0.1) {
    organState.vitality = 0.5;
    return { regenerated: true, newVitality: organState.vitality };
  }

  return { regenerated: false, vitality: organState.vitality };
}

// ============================================================
// EXPORTS
// ============================================================
module.exports = {
  ${moduleName},
  organState,
  maintain,
  computeResonance,
  ${componentExports.map(c => c.name).join(', ')}
};
`;

    return {
      fileName,
      moduleName,
      code: organCode,
      organ,
      componentCount: components.length
    };
  }

  // ============================================================
  // GENERATE COMPONENT CODE
  // Each component becomes an exported function
  // ============================================================
  generateComponentCode(component, name, organDims) {
    const { type, address, dimensions } = component;
    const { base, tone, color, gate, line } = dimensions;

    // Component behavior based on type
    const behaviors = {
      movement_node: `
        // Movement node: active, dynamic, state-changing
        function ${name}(input) {
          const energy = input?.intensity || 0.5;
          const direction = input?.direction || 'forward';

          return {
            type: 'movement',
            energy,
            direction,
            transformed: transformState(input, { base: ${base}, tone: ${tone}, color: ${color} }),
            address: '${address}'
          };
        }

        function transformState(state, dims) {
          if (!state) return dims;
          return {
            ...state,
            base: (state.base + dims.base - 1) % 5 + 1,
            tone: (state.tone + dims.tone - 1) % 6 + 1
          };
        }
      `,

      evolution_edge: `
        // Evolution edge: connects states, facilitates flow
        function ${name}(fromState, toState) {
          const weight = computeEdgeWeight(fromState, toState);

          return {
            type: 'evolution',
            from: fromState,
            to: toState,
            weight,
            address: '${address}',
            active: weight > 0.3
          };
        }

        function computeEdgeWeight(s1, s2) {
          if (!s1 || !s2) return 0.5;
          let w = 0;
          if (s1.base === s2.base) w += 0.3;
          if (s1.tone === s2.tone) w += 0.25;
          if (s1.color === s2.color) w += 0.25;
          if (s1.gate === s2.gate) w += 0.15;
          if (s1.line === s2.line) w += 0.05;
          return w;
        }
      `,

      being_container: `
        // Being container: holds state, maintains identity
        function ${name}(content = null) {
          const container = {
            content,
            capacity: ${base * 10},
            occupied: content ? 1 : 0,
            address: '${address}'
          };

          return {
            type: 'being',
            container,
            fullness: container.occupied / container.capacity,
            canAccept: (item) => container.occupied < container.capacity
          };
        }
      `,

      design_pattern: `
        // Design pattern: structured, precise, rule-based
        function ${name}(input) {
          const rules = generateRules(${JSON.stringify(dimensions)});

          return {
            type: 'design',
            rules,
            apply: (data) => rules.reduce((d, rule) => rule(d), data),
            address: '${address}'
          };
        }

        function generateRules(dims) {
          return [
            (d) => ({ ...d, base: dims.base }),
            (d) => ({ ...d, tone: dims.tone }),
            (d) => ({ ...d, color: dims.color })
          ];
        }
      `,

      space_field: `
        // Space field: ambient, contextual, environmental
        function ${name}(context = {}) {
          const field = {
            intensity: context.intensity || 0.5,
            range: ${base * 20},
            decay: 0.99,
            address: '${address}'
          };

          return {
            type: 'space',
            field,
            affect: (target) => ({ ...target, fieldIntensity: field.intensity }),
            decay: () => { field.intensity *= field.decay; }
          };
        }
      `,

      generic_component: `
        // Generic component: adaptable, neutral
        function ${name}(input) {
          return {
            type: 'generic',
            input,
            address: '${address}',
            dimensions: ${JSON.stringify(dimensions)}
          };
        }
      `
    };

    const behavior = behaviors[type] || behaviors.generic_component;

    return {
      name,
      code: behavior.trim(),
      imports: '' // Components don't need imports by default
    };
  }

  // ============================================================
  // GENERATE MAIN MODULE
  // The entry point that requires all organs and runs the system
  // ============================================================
  generateMainModule(body, organFiles) {
    const imports = organFiles.map(f => 
      `const ${f.moduleName} = require('./${f.fileName}');`
    ).join('\n');

    const organNames = organFiles.map(f => f.moduleName);

    const mainCode = `
/**
 * MRNN Autopoietic System — Generated Entry Point
 * 
 * AUTO-GENERATED by the system's own metabolism.
 * This file requires all organ modules and orchestrates them.
 * 
 * To run: node system.js
 */

${imports}

// ============================================================
// SYSTEM STATE
// ============================================================
const systemState = {
  organs: [${organNames.join(', ')}],
  born: Date.now(),
  tick: 0,
  vitality: ${body.vitality.toFixed(4)},
  connections: ${body.connectionCount}
};

// ============================================================
// SYSTEM ORCHESTRATION
// ============================================================
function runSystem(input = null) {
  systemState.tick++;

  console.log(\`\n=== MRNN System Tick #\${systemState.tick} ===\`);
  console.log(\`Vitality: \${(systemState.vitality * 100).toFixed(1)}% | Organs: \${systemState.organs.length}\`);

  // Activate each organ
  const results = [];
  for (const organ of systemState.organs) {
    try {
      const result = organ(input);
      results.push(result);
      console.log(\`  ✅ \${result.organ.name}: resonance=\${(result.resonance * 100).toFixed(1)}% components=\${result.activeComponents.length}\`);
    } catch (err) {
      console.log(\`  ❌ \${organ.name || 'unknown'}: \${err.message}\`);
    }
  }

  // Compute system vitality
  const avgResonance = results.reduce((s, r) => s + r.resonance, 0) / (results.length || 1);
  systemState.vitality = avgResonance * 0.8 + systemState.vitality * 0.2;

  // Self-maintenance
  for (const organ of systemState.organs) {
    if (typeof organ.maintain === 'function') {
      organ.maintain();
    }
  }

  return {
    tick: systemState.tick,
    vitality: systemState.vitality,
    results,
    timestamp: Date.now()
  };
}

// ============================================================
// AUTOPOIETIC LOOP
// ============================================================
function autopoieticLoop(iterations = 10, delay = 1000) {
  console.log('\n🌱 Starting autopoietic loop...');

  let count = 0;
  const interval = setInterval(() => {
    count++;
    const result = runSystem();

    if (count >= iterations || result.vitality < 0.1) {
      clearInterval(interval);
      console.log('\n*** AUTOPOIETIC LOOP COMPLETE ***');
      console.log(\`Ticks: \${count} | Final vitality: \${(result.vitality * 100).toFixed(1)}%\`);
      process.exit(0);
    }
  }, delay);
}

// ============================================================
// STATUS
// ============================================================
function getStatus() {
  return {
    ...systemState,
    age: Date.now() - systemState.born,
    organDetails: systemState.organs.map(o => ({
      name: o.organState?.name || 'unknown',
      vitality: o.organState?.vitality || 0,
      activations: o.organState?.activations || 0
    }))
  };
}

// ============================================================
// EXPORTS
// ============================================================
module.exports = {
  runSystem,
  autopoieticLoop,
  getStatus,
  systemState
};

// ============================================================
// CLI
// ============================================================
if (require.main === module) {
  const args = process.argv.slice(2);
  const command = args[0] || 'run';

  switch (command) {
    case 'run':
      runSystem();
      break;
    case 'loop':
      autopoieticLoop(parseInt(args[1]) || 10, parseInt(args[2]) || 1000);
      break;
    case 'status':
      console.log(JSON.stringify(getStatus(), null, 2));
      break;
    default:
      console.log('Usage: node system.js [run|loop <n>|status]');
  }
}
`;

    return {
      fileName: 'system.js',
      moduleName: 'system',
      code: mainCode,
      isEntryPoint: true
    };
  }

  // ============================================================
  // GENERATE PACKAGE MANIFEST
  // ============================================================
  generatePackageManifest(body, organFiles) {
    const manifest = {
      name: 'mrnn-generated-system',
      version: '1.0.0',
      description: 'Auto-generated autopoietic system',
      main: 'system.js',
      generatedAt: new Date().toISOString(),
      organs: organFiles.map(f => ({
        name: f.moduleName,
        file: f.fileName,
        circuit: f.organ.circuit,
        vitality: f.organ.vitality,
        components: f.organ.components.length
      })),
      system: {
        vitality: body.vitality,
        connections: body.connectionCount,
        autopoietic: body.vitality > 0.3 && body.organCount >= 3
      }
    };

    return {
      fileName: 'manifest.json',
      code: JSON.stringify(manifest, null, 2),
      isJson: true
    };
  }

  // ============================================================
  // WRITE FILES
  // ============================================================
  async writeFiles(files) {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }

    for (const file of files) {
      const filePath = path.join(this.outputDir, file.fileName);
      fs.writeFileSync(filePath, file.code);
      this.generatedFiles.push(filePath);
      console.log(`   → ${file.fileName}`);
    }
  }

  // ============================================================
  // VERIFY EXECUTABILITY
  // Try to require() the generated files to verify they work
  // ============================================================
  async verifyExecutability() {
    const results = [];

    for (const filePath of this.generatedFiles) {
      if (filePath.endsWith('.js')) {
        try {
          // Clear require cache
          delete require.cache[require.resolve(filePath)];
          const module = require(filePath);

          results.push({
            file: path.basename(filePath),
            loadable: true,
            exports: Object.keys(module),
            error: null
          });
        } catch (err) {
          results.push({
            file: path.basename(filePath),
            loadable: false,
            exports: [],
            error: err.message
          });
        }
      }
    }

    const allLoadable = results.every(r => r.loadable);

    if (allLoadable) {
      console.log('   ✅ All files verified executable');
    } else {
      const failed = results.filter(r => !r.loadable);
      console.log(`   ❌ ${failed.length} files failed verification`);
      for (const f of failed) {
        console.log(`      → ${f.file}: ${f.error}`);
      }
    }

    return { allLoadable, results };
  }

  // ============================================================
  // PARSE ADDRESS
  // ============================================================
  parseAddress(address) {
    const match = address.match(/B(\d+)\.T(\d+)\.C(\d+)\.G(\d+)\.L(\d+)/);
    if (!match) return null;
    return {
      base: parseInt(match[1]),
      tone: parseInt(match[2]),
      color: parseInt(match[3]),
      gate: parseInt(match[4]),
      line: parseInt(match[5])
    };
  }
}

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MRNNCodeGenerator };
}
